services:
  backend:
    build: ./
    container_name: sociality
    working_dir: /sociality
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    command:
      - ./commands/start_server_${MODE}.sh
    volumes:
      - ./src:/sociality/src
      - ./commands:/sociality/commands/
      - static_content:/sociality/src/static
      - media_content:/sociality/src/user_content
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres


  mongo:
    image: mongo
    restart: always
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/sociality/src/static
      - media_content:/sociality/src/user_content
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    depends_on:
      - backend



volumes:
  pg_data: { }
  pgadmin: { }
  mongo_data: { }
  static_content: { }
  media_content: { }