# Generated by Django 5.0.6 on 2024-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_file",
            field=models.FileField(upload_to="blog/posts/"),
        ),
        migrations.AlterField(
            model_name="story",
            name="media_file",
            field=models.FileField(upload_to="blog/stories/"),
        ),
    ]
