# Generated by Django 5.0.6 on 2024-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_media_file_alter_story_media_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="expire_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expire date"
            ),
        ),
    ]
