# Generated by Django 5.0.6 on 2024-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.jpg", upload_to="avatars/users/"
            ),
        ),
    ]
